name: Checks

on:
  pull_request:
  push:

jobs:
  flake-show:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - id: set-matrix
        name: Evaluate flake
        run: nix flake show --all-systems
